version: '3'
services:

  dev-daemon:
    image: "node:11.9"
    command: tail -f /dev/null
    volumes:
      - "..:/app"

  mongo:
    image: mongo:3.6.10

  api:
    image: node:11.9
    depends_on:
      - mongo
    ports:
      - "9000:80"
    working_dir: /app
    volumes:
      - "../api:/app"
    environment:
      SPLIGHT_MONGODB_URL: "mongodb://mongo:27017/"
      SPLIGHT_INSTANCE_NAME: "développement"
      SPLIGHT_INSTANCE_WARNINGS: "les données sont stockées dans git\nelles sont restaurées au démarrage et sauvées à l’arrêt"
    command: npm run serve

  public-frontend:
    image: node:11.9
    depends_on:
      - api
    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      - "../public-frontend:/app"
    command: npm run serve

  admin-frontend:
    image: node:11.9
    depends_on:
      - api
    ports:
      - "8081:8080"
    working_dir: /app
    volumes:
      - "../admin-frontend:/app"
    command: npm run serve
