permalink: pretty
baseurl: /splight.fr

markdown: kramdown
kramdown:
  parse_block_html: true

sass:
    style: compressed

defaults:
  - scope:
      path: "_music_weeks"
    values:
      layout: "music_week"

collections:
  music_weeks:
    output: true
    permalink: /musique/:name/

exclude:
  - README.md
