permalink: pretty

markdown: kramdown
kramdown:
  parse_block_html: true

sass:
    style: compressed

defaults:
  - scope:
      path: ""
    values:
      layout: all
  - scope:
      path: _music_weeks
    values:
      layout: music_week
      category: Musique

collections:
  sections:
    output: true
    permalink: /:name/
  music_weeks:
    output: true
    permalink: /musique/:name/

exclude:
  - README.md
  - run_development_cycle.sh
